package apache

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/adialaleal/odins/internal/state"
	"github.com/adrg/xdg"
)

var vhostTmpl = template.Must(template.New("apache-vhost").Parse(`# Generated by ODINS — do not edit manually
<VirtualHost *:80>
    ServerName {{ .Subdomain }}
    Redirect permanent / https://{{ .Subdomain }}/
</VirtualHost>

<VirtualHost *:443>
    ServerName {{ .Subdomain }}

    SSLEngine on
    SSLCertificateFile     {{ .CertPath }}
    SSLCertificateKeyFile  {{ .KeyPath }}

    ProxyPreserveHost On
    ProxyPass         / http://{{ .Upstream }}/
    ProxyPassReverse  / http://{{ .Upstream }}/

    RequestHeader set X-Real-IP "%{REMOTE_ADDR}e"
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}e"
    RequestHeader set X-Forwarded-Proto "https"
</VirtualHost>
`))

type vhostData struct {
	Subdomain string
	Upstream  string
	CertPath  string
	KeyPath   string
}

func confDir() string {
	return filepath.Join(xdg.ConfigHome, "odins", "apache", "vhosts")
}

func certDir() string {
	return filepath.Join(xdg.ConfigHome, "odins", "certs")
}

func writeVhost(r state.Route) error {
	if err := os.MkdirAll(confDir(), 0755); err != nil {
		return err
	}

	upstream := fmt.Sprintf("127.0.0.1:%d", r.Port)
	if r.DockerContainer != "" {
		upstream = fmt.Sprintf("%s:%d", r.DockerContainer, r.Port)
	}

	data := vhostData{
		Subdomain: r.Subdomain,
		Upstream:  upstream,
		CertPath:  filepath.Join(certDir(), r.Subdomain+".pem"),
		KeyPath:   filepath.Join(certDir(), r.Subdomain+"-key.pem"),
	}

	path := filepath.Join(confDir(), r.Subdomain+".conf")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return vhostTmpl.Execute(f, data)
}

func removeVhost(subdomain string) error {
	path := filepath.Join(confDir(), subdomain+".conf")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
