package dns

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/adrg/xdg"
)

// DnsmasqConfPath returns the path to the ODINS-managed dnsmasq.conf (XDG).
func DnsmasqConfPath() string {
	return filepath.Join(xdg.ConfigHome, "odins", "dnsmasq.conf")
}

// brewDnsmasqPaths returns the canonical Homebrew dnsmasq config paths to try.
func brewDnsmasqPaths() []string {
	return []string{
		"/opt/homebrew/etc/dnsmasq.conf",
		"/usr/local/etc/dnsmasq.conf",
	}
}

// buildConfigContent returns the dnsmasq config content for the given TLDs and port.
func buildConfigContent(tlds []string, port int) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ODINS — do not edit manually\n")
	sb.WriteString("listen-address=127.0.0.1\n")
	sb.WriteString(fmt.Sprintf("port=%d\n", port))
	sb.WriteString("no-resolv\n")
	sb.WriteString("bind-interfaces\n")
	sb.WriteString("expand-hosts\n\n")
	for _, tld := range tlds {
		sb.WriteString(fmt.Sprintf("address=/.%s/127.0.0.1\n", tld))
	}
	return sb.String()
}

// GenerateConfig writes the dnsmasq config to the XDG path AND directly to the
// Homebrew location. Writing directly (not symlinking) prevents broken-link failures
// when the XDG config directory is removed or recreated.
func GenerateConfig(tlds []string, port int) error {
	content := buildConfigContent(tlds, port)

	// 1. Write to XDG path (our canonical source)
	xdgPath := DnsmasqConfPath()
	if err := os.MkdirAll(filepath.Dir(xdgPath), 0755); err != nil {
		return fmt.Errorf("create odins config dir: %w", err)
	}
	if err := os.WriteFile(xdgPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write dnsmasq config: %w", err)
	}

	// 2. Write directly to Homebrew path(s) so dnsmasq picks it up
	written := false
	for _, brewPath := range brewDnsmasqPaths() {
		if _, err := os.Stat(filepath.Dir(brewPath)); err == nil {
			if err := os.WriteFile(brewPath, []byte(content), 0644); err == nil {
				written = true
				break
			}
		}
	}
	if !written {
		return fmt.Errorf("could not write to Homebrew dnsmasq config directory")
	}
	return nil
}

// LinkConfig is kept for compatibility but now just calls GenerateConfig internally.
// Direct writes are preferred over symlinks to prevent broken-link failures.
func LinkConfig() error {
	// No-op: GenerateConfig now writes directly to both paths.
	return nil
}
