package dns

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/adrg/xdg"
)

// DnsmasqConfPath returns the path to the ODINS-managed dnsmasq.conf.
func DnsmasqConfPath() string {
	return filepath.Join(xdg.ConfigHome, "odins", "dnsmasq.conf")
}

// GenerateConfig writes the dnsmasq config file for the given TLDs and port.
func GenerateConfig(tlds []string, port int) error {
	dir := filepath.Dir(DnsmasqConfPath())
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Generated by ODINS — do not edit manually\n")
	sb.WriteString("listen-address=127.0.0.1\n")
	sb.WriteString(fmt.Sprintf("port=%d\n", port))
	sb.WriteString("no-resolv\n")
	sb.WriteString("expand-hosts\n\n")

	for _, tld := range tlds {
		sb.WriteString(fmt.Sprintf("address=/.%s/127.0.0.1\n", tld))
	}

	return os.WriteFile(DnsmasqConfPath(), []byte(sb.String()), 0644)
}

// LinkConfig symlinks ODINS dnsmasq.conf to the Homebrew dnsmasq config location.
// This ensures dnsmasq picks up our config on startup.
func LinkConfig() error {
	// Homebrew dnsmasq config locations
	targets := []string{
		"/usr/local/etc/dnsmasq.conf",
		"/opt/homebrew/etc/dnsmasq.conf",
	}

	src := DnsmasqConfPath()
	for _, target := range targets {
		if _, err := os.Stat(filepath.Dir(target)); err == nil {
			// Backup original if it exists and isn't already our symlink
			if info, err := os.Lstat(target); err == nil {
				if info.Mode()&os.ModeSymlink == 0 {
					backup := target + ".odins-backup"
					if err := os.Rename(target, backup); err != nil {
						return fmt.Errorf("backup dnsmasq.conf: %w", err)
					}
				} else {
					// Remove existing symlink
					os.Remove(target)
				}
			}
			return os.Symlink(src, target)
		}
	}
	return fmt.Errorf("could not find Homebrew dnsmasq config directory")
}
