package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/adialaleal/odins/internal/state"
	"github.com/adrg/xdg"
)

var vhostTmpl = template.Must(template.New("nginx-vhost").Parse(`# Generated by ODINS — do not edit manually
server {
    listen 80;
    server_name {{ .Subdomain }};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name {{ .Subdomain }};

    ssl_certificate     {{ .CertPath }};
    ssl_certificate_key {{ .KeyPath }};

    location / {
        proxy_pass         http://{{ .Upstream }};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
`))

type vhostData struct {
	Subdomain string
	Upstream  string
	CertPath  string
	KeyPath   string
}

func confDir() string {
	return filepath.Join(xdg.ConfigHome, "odins", "nginx", "conf.d")
}

func certDir() string {
	return filepath.Join(xdg.ConfigHome, "odins", "certs")
}

func writeVhost(r state.Route) error {
	if err := os.MkdirAll(confDir(), 0755); err != nil {
		return err
	}

	upstream := fmt.Sprintf("127.0.0.1:%d", r.Port)
	if r.DockerContainer != "" {
		upstream = fmt.Sprintf("%s:%d", r.DockerContainer, r.Port)
	}

	data := vhostData{
		Subdomain: r.Subdomain,
		Upstream:  upstream,
		CertPath:  filepath.Join(certDir(), r.Subdomain+".pem"),
		KeyPath:   filepath.Join(certDir(), r.Subdomain+"-key.pem"),
	}

	path := filepath.Join(confDir(), r.Subdomain+".conf")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return vhostTmpl.Execute(f, data)
}

func removeVhost(subdomain string) error {
	path := filepath.Join(confDir(), subdomain+".conf")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
